### ISSUE TITLE
running

### ISSUE THREAD

**Issue by vtanguturi** [kushalvyas/Python-Multiple-Image-Stitching#3]
I cloned your repository, and am trying to run it. However, it's taken a long time and simply shows 1 image and seems to be stuck at "init done" phase. How long should the whole program take to finish running?

**Comment by kushalvyas** [comment]
the program is just a simple tutorial in python. not intended for any deployment purposes. It will take a lot of time, as I'm using simply for loops to iterate over each pixel of the image multiple times. Since the program is just for the purposes of understanding, I advise not to use it much for deployment purposes or any similar use cases.
